---
- hosts: localhost
  become: yes
  tasks:
  - name: Include OS-specific variables.
    include_vars: "{{ playbook_dir }}/defaults/main.yml"
  - import_tasks: "tasks/main.yml"
  - import_tasks: "tasks/vagrant_inventory.yml"
